### ISSUE TITLE
vcert 5.5

### ISSUE THREAD

**Issue by hawksight** [Venafi/homebrew-tap#25]
**BUSINESS PROBLEM**

The latest `vcert` release isn't available via homebrew yet.

https://github.com/Venafi/vcert/releases/tag/v5.5.0

**PROPOSED SOLUTION**

Include it in the tap here?

**CURRENT ALTERNATIVES**

Manual hell

**VENAFI EXPERIENCE**

I work for Venafi :)

**Comment by zosocanuck** [comment]
Resolved via #26
